/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-sans)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      fontSize: {
        h1: ['var(--type-h1-size)', { lineHeight: 'var(--type-h1-line)' }],
        h2: ['var(--type-h2-size)', { lineHeight: 'var(--type-h2-line)' }],
        h3: ['var(--type-h3-size)', { lineHeight: 'var(--type-h3-line)' }],
        body: ['var(--type-body-size)', { lineHeight: 'var(--type-body-line)' }],
        'body-sm': ['var(--type-body-sm-size)', { lineHeight: 'var(--type-body-sm-line)' }],
      },
      colors: {
        brand: 'var(--brand, #0fb5d7)',
        bg: 'var(--bg-surface, var(--bg-0))',
        panel: 'var(--panel-surface, var(--bg-1))',
        border: 'var(--surface-border, var(--stroke-1))',
        text: 'var(--text-strong, var(--text-1))',
        'bg-0': 'var(--bg-0)',
        'bg-1': 'var(--bg-1)',
        'bg-2': 'var(--bg-2)',
        'stroke-1': 'var(--stroke-1)',
        'stroke-2': 'var(--stroke-2)',
        'text-1': 'var(--text-1)',
        'text-2': 'var(--text-2)',
        'text-3': 'var(--text-3)',
        'accent-cyan': 'var(--accent-cyan)',
        'accent-blue': 'var(--accent-blue)',
        'ok-green': 'var(--ok-green)',
        'warn-amber': 'var(--warn-amber)',
        'danger-red': 'var(--danger-red)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        popover: 'var(--popover)',
        'popover-foreground': 'var(--popover-foreground)',
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        destructive: 'var(--destructive)',
        'destructive-foreground': 'var(--destructive-foreground)',
        input: 'var(--input)',
        ring: 'var(--ring)',
      },
      borderRadius: {
        sm: 'var(--r-sm, 8px)',
        md: 'var(--r-md, 10px)',
        lg: '12px',
        xl: '16px',
      },
      boxShadow: {
        card: '0 18px 46px rgba(10, 18, 38, 0.08), 0 6px 18px rgba(10, 18, 38, 0.04)',
        'glow-cyan': 'var(--glow-cyan)',
        'glow-amber': 'var(--glow-amber)',
        'glow-red': 'var(--glow-red)',
      },
      transitionDuration: {
        micro: 'var(--motion-micro)',
        standard: 'var(--motion-standard)',
        page: 'var(--motion-page)',
      },
      transitionTimingFunction: {
        engine: 'var(--ease-spring)',
      },
      spacing: {
        grid: 'var(--grid-unit)',
        'space-1': 'var(--space-1)',
        'space-2': 'var(--space-2)',
        'space-3': 'var(--space-3)',
        'space-4': 'var(--space-4)',
        'space-5': 'var(--space-5)',
        'space-6': 'var(--space-6)',
        'space-8': 'var(--space-8)',
        'space-10': 'var(--space-10)',
        'space-12': 'var(--space-12)',
        'space-16': 'var(--space-16)',
        'space-20': 'var(--space-20)',
        section: 'var(--section-padding)',
        'section-mobile': 'var(--section-padding-mobile)',
        card: 'var(--card-padding)',
        'table-row': 'var(--table-row-height)',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
};
